require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DesignVersionsController do

  # This should return the minimal set of attributes required to create a valid
  # DesignVersion. As you add validations to DesignVersion, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {  }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DesignVersionsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all design_versions as @design_versions" do
      design_version = DesignVersion.create! valid_attributes
      get :index, {}, valid_session
      assigns(:design_versions).should eq([design_version])
    end
  end

  describe "GET show" do
    it "assigns the requested design_version as @design_version" do
      design_version = DesignVersion.create! valid_attributes
      get :show, {:id => design_version.to_param}, valid_session
      assigns(:design_version).should eq(design_version)
    end
  end

  describe "GET new" do
    it "assigns a new design_version as @design_version" do
      get :new, {}, valid_session
      assigns(:design_version).should be_a_new(DesignVersion)
    end
  end

  describe "GET edit" do
    it "assigns the requested design_version as @design_version" do
      design_version = DesignVersion.create! valid_attributes
      get :edit, {:id => design_version.to_param}, valid_session
      assigns(:design_version).should eq(design_version)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DesignVersion" do
        expect {
          post :create, {:design_version => valid_attributes}, valid_session
        }.to change(DesignVersion, :count).by(1)
      end

      it "assigns a newly created design_version as @design_version" do
        post :create, {:design_version => valid_attributes}, valid_session
        assigns(:design_version).should be_a(DesignVersion)
        assigns(:design_version).should be_persisted
      end

      it "redirects to the created design_version" do
        post :create, {:design_version => valid_attributes}, valid_session
        response.should redirect_to(DesignVersion.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved design_version as @design_version" do
        # Trigger the behavior that occurs when invalid params are submitted
        DesignVersion.any_instance.stub(:save).and_return(false)
        post :create, {:design_version => {  }}, valid_session
        assigns(:design_version).should be_a_new(DesignVersion)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DesignVersion.any_instance.stub(:save).and_return(false)
        post :create, {:design_version => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested design_version" do
        design_version = DesignVersion.create! valid_attributes
        # Assuming there are no other design_versions in the database, this
        # specifies that the DesignVersion created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DesignVersion.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => design_version.to_param, :design_version => { "these" => "params" }}, valid_session
      end

      it "assigns the requested design_version as @design_version" do
        design_version = DesignVersion.create! valid_attributes
        put :update, {:id => design_version.to_param, :design_version => valid_attributes}, valid_session
        assigns(:design_version).should eq(design_version)
      end

      it "redirects to the design_version" do
        design_version = DesignVersion.create! valid_attributes
        put :update, {:id => design_version.to_param, :design_version => valid_attributes}, valid_session
        response.should redirect_to(design_version)
      end
    end

    describe "with invalid params" do
      it "assigns the design_version as @design_version" do
        design_version = DesignVersion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DesignVersion.any_instance.stub(:save).and_return(false)
        put :update, {:id => design_version.to_param, :design_version => {  }}, valid_session
        assigns(:design_version).should eq(design_version)
      end

      it "re-renders the 'edit' template" do
        design_version = DesignVersion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DesignVersion.any_instance.stub(:save).and_return(false)
        put :update, {:id => design_version.to_param, :design_version => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested design_version" do
      design_version = DesignVersion.create! valid_attributes
      expect {
        delete :destroy, {:id => design_version.to_param}, valid_session
      }.to change(DesignVersion, :count).by(-1)
    end

    it "redirects to the design_versions list" do
      design_version = DesignVersion.create! valid_attributes
      delete :destroy, {:id => design_version.to_param}, valid_session
      response.should redirect_to(design_versions_url)
    end
  end

end
